### ISSUE TITLE
Backup instructions for /etc/gitlab don't work

### ISSUE THREAD

**Issue by gokeefe** [pivotal-cf/docs-gitlab#17]
The backup instructions eventually lead to [this page](https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/doc/settings/backups.md#backup-and-restore-omnibus-gitlab-configuration), but the instructions don't appear to work when /etc/gitlab is a symlink, as it is in the GitLab tile.

**Comment by gokeefe** [comment]
Example:

`
# id
uid=0(root) gid=0(root) groups=0(root)
gitlab_ee/631037ab-430a-49ee-8e68-eb26f3b45a7f:~# ls -ald /etc/gitlab
lrwxrwxrwx 1 root root 31 Jul 22 03:16 /etc/gitlab -> /var/vcap/nfs/shared/etc/gitlab

gitlab_ee/631037ab-430a-49ee-8e68-eb26f3b45a7f:~# sh -c 'umask 0077; tar -cf $(date "+etc-gitlab-%s.tar") -C / etc/gitlab'

gitlab_ee/631037ab-430a-49ee-8e68-eb26f3b45a7f:~# tar -tvf etc-gitlab-1502739814.tar
lrwxrwxrwx root/root         0 2017-07-22 03:16 etc/gitlab -> /var/vcap/nfs/shared/etc/gitlab

gitlab_ee/631037ab-430a-49ee-8e68-eb26f3b45a7f:~# sh -c 'umask 0077; tar -cf $(date "+etc-gitlab-%s.tar") -h /etc/gitlab'
tar: Removing leading `/' from member names

gitlab_ee/631037ab-430a-49ee-8e68-eb26f3b45a7f:~# tar -tvf etc-gitlab-1502739814.tar
lrwxrwxrwx root/root         0 2017-07-22 03:16 etc/gitlab -> /var/vcap/nfs/shared/etc/gitlab

gitlab_ee/631037ab-430a-49ee-8e68-eb26f3b45a7f:~# tar -tvf etc-gitlab-1502739833.tar
drwxrwxr-x root/root         0 2017-08-14 19:29 etc/gitlab/
-rw------- root/root     63642 2017-07-22 03:19 etc/gitlab/gitlab.rb
drwxr-xr-x root/root         0 2017-01-05 05:06 etc/gitlab/trusted-certs/
-rw------- root/root      9740 2017-07-22 03:19 etc/gitlab/gitlab-secrets.json
`

**Comment by jncd** [comment]
Hello @lambertjosh and @maxlazio 
You've made PRs recently for the Gitlab doc. Do you work for Gitlab? 
Can you help out @gokeefe with these back-up instructions and make another PR to fix the docs?
Thanks!
